export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const VARIFY_OTP = "VARIFY_OTP";
export const VARIFY_OTP_SUCCESS = "VARIFY_OTP_SUCCESS";
export const VARIFY_OTP_FAILURE = "VARIFY_OTP_FAILURE";

export const RESEND_OTP = "RESEND_OTP";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAILURE = "RESEND_OTP_FAILURE";

export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAILURE = "FORGET_PASSWORD_FAILURE";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";


export const PICK_UP_POINT_LIST = "PICK_UP_POINT_LIST";
export const PICK_UP_POINT_LIST_SUCCESS = "PICK_UP_POINT_LIST_SUCCESS";
export const PICK_UP_POINT_LIST_FAILURE = "PICK_UP_POINT_LIST_FAILURE";

export const SAVE_PICK_UP_POINT_LIST = "SAVE_PICK_UP_POINT_LIST";

export const INITIALIZE_VIEWCART_DATA = "INITIALIZE_VIEWCART_DATA";
export const REMOVE_ALL = "REMOVE_ALL";
export const REMOVE_INDEX_ELEMENT = "REMOVE_INDEX_ELEMENT";
export const INCREMENT_DECREMENT_VALUE = "INCREMENT_DECREMENT_VALUE";

export const PIN_CODE_CALL = "PIN_CODE_CALL";
export const PIN_CODE_CALL_SUCCESS = "PIN_CODE_CALL_SUCCESS";
export const PIN_CODE_CALL_FAILURE = "PIN_CODE_CALL_FAILURE";

export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILURE = "PRODUCT_LIST_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const CAROUSEl_DATA = "CAROUSEl_DATA";
export const CAROUSEl_DATA_SUCCESS = "CAROUSEl_DATA_SUCCESS";
export const CAROUSEl_DATA_FAILURE = "CAROUSEl_DATA_FAILURE";

export const PLACE_ORDER = "PLACE_ORDER";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE";

// export const ADD_TO_CART_LIST_DATA = "ADD_TO_CART_LIST_DATA";

export const SEARCH_TEXT = "SEARCH_TEXT";

export const RESET = "RESET";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const SELECT_ADDRESS = "SELECT_ADDRESS";

export const CLEAR_LIST_DATA = "CLEAR_LIST_DATA";
